[project]
name = "pocforge-web-backend"
version = "0.1.0"
description = "Web backend for PoCForge"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.32.0",
    "pydantic>=2.10.0",
    "python-multipart>=0.0.12"
]
